version: "2"

services:
  dynamodb:
    image: "openjdk:8-jre-alpine"
    expose:
      - "8000"
    ports:
      - "8000:8000"
    volumes:
      - "./packages:/opt/dynamodb"
      - "dynamodb_databases:/data"
    command:
      - "java"
      - "-Djava.library.path=/opt/dynamodb/DynamoDBLocal_lib"
      - "-jar"
      - "/opt/dynamodb/DynamoDBLocal.jar"
      - "-sharedDb"
      - "-dbPath"
      - "/data"

volumes:
  dynamodb_databases:
    driver: local
