version: "2"

services:
  mysql:
    image: "mysql:5.7"
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
    volumes:
      - "mysql:/var/lib/mysql"
    ports:
      - "3306:3306"
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"

volumes:
  mysql:
    driver: local
